# Generated by Django 4.2.3 on 2023-10-02 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty', models.CharField(choices=[('ФИТиУ', 'Факультет информационных технологий и инженерии'), ('ЮФ', 'Юридический факультет'), ('ФЭиУ', 'Факультет экономики и управления'), ('ФИЯ', 'Факультет иностранных языков'), ('ФДО', 'Факультет дополнительного образования')], max_length=32)),
                ('EducationLevel', models.CharField(choices=[('Б', 'Бакалавр'), ('С', 'Специалитет'), ('М', 'Магистратура')], max_length=1)),
                ('EducationForm', models.CharField(choices=[('О', 'Очная форма'), ('З', 'Заочная форма'), ('ОЗ', 'Очно-заочная форма'), ('ДИСТ', 'Дистанционная форма')], default='О', max_length=4)),
                ('EduProgram', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['Faculty', 'EducationLevel', 'EducationForm', 'EduProgram'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.IntegerField(default=1)),
                ('Stream', models.IntegerField(default=1)),
                ('GroupNum', models.IntegerField(default=1)),
                ('SubGroup', models.IntegerField(blank=True, null=True)),
                ('EduProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.education_program')),
            ],
            options={
                'ordering': ['EduProgram', 'Course', 'Stream', 'GroupNum'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TermNum', models.IntegerField()),
                ('TermStart', models.DateField(blank=True)),
                ('TermEnd', models.DateField(blank=True)),
            ],
            options={
                'ordering': ['TermStart'],
            },
        ),
        migrations.CreateModel(
            name='Student_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateStart', models.DateField(blank=True)),
                ('DateEnd', models.DateField(blank=True)),
                ('scheduleFile', models.JSONField()),
                ('Term_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.term')),
                ('scheduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group')),
            ],
            options={
                'ordering': ['Term_num', 'DateStart'],
            },
        ),
    ]
