# Generated by Django 4.2.3 on 2023-08-10 14:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationLevel', models.CharField(choices=[('К', 'Колледж'), ('Б', 'Бакалавр'), ('С', 'Специалитет'), ('М', 'Магистратура')], max_length=1)),
                ('EducationForm', models.CharField(choices=[('О', 'Очная форма'), ('З', 'Заочная форма'), ('ОЗ', 'Очно-заочная форма'), ('ДИСТ', 'Дистанционная форма')], default='О', max_length=4)),
                ('Course', models.IntegerField(default=1)),
                ('Group', models.IntegerField(default=1)),
                ('Stream', models.IntegerField(default=1)),
                ('SubGroup', models.IntegerField(default=1)),
                ('LabGroup', models.IntegerField(default=1)),
                ('PracticeGroup', models.IntegerField(default=1)),
                ('Schedule', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('TermNum', models.IntegerField(primary_key=True, serialize=False)),
                ('TermStart', models.DateField(default=datetime.date(2023, 9, 1))),
                ('TermEnd', models.DateField(default=datetime.date(2023, 12, 31))),
            ],
        ),
        migrations.CreateModel(
            name='UniqueSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChangingDateStart', models.DateField(auto_now_add=True)),
                ('ChangingDateEnd', models.DateField(auto_now_add=True)),
                ('Schedule', models.JSONField()),
                ('Schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedules')),
            ],
        ),
        migrations.AddField(
            model_name='schedules',
            name='TermNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.terms'),
        ),
    ]
