# Generated by Django 4.2.3 on 2023-10-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_schedule',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
