# Generated by Django 4.2.3 on 2023-08-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='EduProgram',
            field=models.CharField(default='None', max_length=256),
        ),
    ]
