# Generated by Django 4.2.3 on 2023-10-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_teacher_schedule_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_schedule',
            name='last_update',
        ),
    ]
