# Generated by Django 4.2.3 on 2023-08-14 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedules_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueschedules',
            name='ChangingDateEnd',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 13, 43, 57, 396472, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='uniqueschedules',
            name='ChangingDateStart',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 13, 43, 57, 396301, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='uniqueschedules',
            name='Schedule',
            field=models.JSONField(default={}),
        ),
    ]
