# Generated by Django 4.2.3 on 2023-10-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_teacher_schedule_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='schedule_view_name',
            field=models.CharField(blank=True, default='<django.db.models.fields.charfield> <.<.', max_length=64, null=True),
        ),
    ]
