# Generated by Django 4.2.3 on 2023-10-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_teacher_schedule_view_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_schedule',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='student_schedule',
            name='lastupdate',
        ),
    ]
