# Generated by Django 4.2.3 on 2023-10-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_student_schedule_date_add_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('teacher_department', 'first_name', 'second_name', 'last_name')},
        ),
    ]
