# Generated by Django 4.2.3 on 2023-10-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_teacher_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_schedule',
            name='teacher_schedule_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher_schedule',
            name='teacher_schedule_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher_schedule',
            name='teacher_schedule_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.term'),
        ),
    ]
