# Generated by Django 4.2.3 on 2023-10-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_teacher_schedule_teacher_schedule_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_schedule',
            name='teacher_schedule_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher_schedule',
            name='teacher_schedule_start',
            field=models.DateField(null=True),
        ),
    ]
