# Generated by Django 4.2.3 on 2023-10-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_teacher_schedule_teacher_schedule_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_schedule',
            name='teacher_schedule_term',
        ),
    ]
