# Generated by Django 4.2.3 on 2023-10-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_remove_teacher_schedule_teacher_schedule_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_program',
            name='education_level',
            field=models.CharField(choices=[('К', 'Колледж'), ('Б', 'Бакалавр'), ('С', 'Специалитет'), ('М', 'Магистратура')], max_length=1),
        ),
    ]
