# Generated by Django 4.2.7 on 2023-12-04 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_alter_education_program_education_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_schedule',
            options={'ordering': ['term_num', 'date_start', 'date_end']},
        ),
        migrations.AddField(
            model_name='teacher_schedule',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 31), null=True),
        ),
        migrations.AddField(
            model_name='teacher_schedule',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 1), null=True),
        ),
    ]
